version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: main
    ports:
      -  "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: docker_phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database

  mailhog:
    image: mailhog/mailhog
    container_name: docker_mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
